"use client"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Header";
import { usePathname } from "next/navigation";
import { Provider } from 'react-redux';
import store,{persistor} from '@/redux/store/configureStore';
import { PersistGate } from 'redux-persist/integration/react';
import Loader from "@/Components/loader";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

   const pathname = usePathname();

  // Define paths where header should be hidden
  const hideHeader = pathname === "/login" || pathname === "/register";

  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >

     <Provider store={store}>
       <PersistGate loading={<Loader/>} persistor={persistor}>
       {hideHeader ? null :
      <Header/>
       }
          {children}
          </PersistGate>
        </Provider>
      </body>
    </html>
  );
}



